package remotesqlite.server;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.NClob;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;
import javax.naming.NamingException;
import javax.sql.rowset.CachedRowSet;
import javax.sql.rowset.RowSetMetaDataImpl;

/**
 * JMX MBean interface for serving remote sqlite connection.
 * 
 * @author Attila Halasz
 * 
 * */
public interface RemoteSqliteMBean {

	public CachedRowSet					getCachedRowSet						(String resultSetId) throws SQLException;
	
	public String						driverConnect						(String environment) throws NamingException, SQLException;
	
//	+: implemented in client side
//	-: not implemented in SQLite or SQLFeatureNotSupportedException, or not implemented as remote SQLite feature

//	+public <T> T						connectionUnwrap					(String connectionId, Class<T> iface) throws SQLException;
//	+public boolean						connectionIsWrapperFor				(String connectionId, Class<?> iface) throws SQLException;
	public String /*Statement*/			connectionCreateStatement			(String connectionId) throws SQLException;
	public String /*PreparedStatement*/	connectionPrepareStatement			(String connectionId, String sql) throws SQLException;
//	-public CallableStatement			connectionPrepareCall				(String connectionId, String sql) throws SQLException;
//	+public String						connectionNativeSQL					(String connectionId, String sql) throws SQLException;
	public void							connectionSetAutoCommit				(String connectionId, boolean autoCommit) throws SQLException;
	public boolean						connectionGetAutoCommit				(String connectionId) throws SQLException;
	public void							connectionCommit					(String connectionId) throws SQLException;
	public void							connectionRollback					(String connectionId) throws SQLException;
	public void							connectionClose						(String connectionId) throws SQLException;
	public boolean						connectionIsClosed					(String connectionId) throws SQLException;
	public String /*DatabaseMetaData*/	connectionGetMetaData				(String connectionId) throws SQLException;
	public void							connectionSetReadOnly				(String connectionId, boolean readOnly) throws SQLException;
	public boolean						connectionIsReadOnly				(String connectionId) throws SQLException;
	public void							connectionSetCatalog				(String connectionId, String catalog) throws SQLException;
	public String						connectionGetCatalog				(String connectionId) throws SQLException;
	public void							connectionSetTransactionIsolation	(String connectionId, int level) throws SQLException;
	public int							connectionGetTransactionIsolation	(String connectionId) throws SQLException;
//	-public SQLWarning					connectionGetWarnings				(String connectionId) throws SQLException;
//	-public void						connectionClearWarnings				(String connectionId) throws SQLException;
	public String /*Statement*/			connectionCreateStatement2			(String connectionId, int resultSetType, int resultSetConcurrency) throws SQLException;
	public String /*PreparedStatement*/	connectionPrepareStatement2			(String connectionId, String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
//	-public CallableStatement			connectionPrepareCall				(String connectionId, String sql, int resultSetType, int resultSetConcurrency) throws SQLException;
	public Map<String, Class<?>>		connectionGetTypeMap				(String connectionId) throws SQLException;
	public void							connectionSetTypeMap				(String connectionId, Map<String, Class<?>> map) throws SQLException;
	public void							connectionSetHoldability			(String connectionId, int holdability) throws SQLException;
	public int							connectionGetHoldability			(String connectionId) throws SQLException;
	public String /*Savepoint*/			connectionSetSavepoint				(String connectionId) throws SQLException;
	public String /*Savepoint*/			connectionSetSavepoint2				(String connectionId, String name) throws SQLException;
	public void							connectionRollback2					(String connectionId, /*Savepoint savepoint*/ String savepointId) throws SQLException;
	public void							connectionReleaseSavepoint			(String connectionId, /*Savepoint savepoint*/ String savepointId) throws SQLException;
	public String /*Statement*/			connectionCreateStatement3			(String connectionId, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
	public String /*PreparedStatement*/	connectionPrepareStatement3			(String connectionId, String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
//	-public CallableStatement			connectionPrepareCall				(String connectionId, String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;
	public String /*PreparedStatement*/	connectionPrepareStatement4			(String connectionId, String sql, int autoGeneratedKeys) throws SQLException;
	public String /*PreparedStatement*/	connectionPrepareStatement5			(String connectionId, String sql, int[] columnIndexes) throws SQLException;
	public String /*PreparedStatement*/	connectionPrepareStatement6			(String connectionId, String sql, String[] columnNames) throws SQLException;
//	-public Clob						connectionCreateClob				(String connectionId) throws SQLException;
//	-public Blob						connectionCreateBlob				(String connectionId) throws SQLException;
//	-public NClob						connectionCreateNClob				(String connectionId) throws SQLException;
//	-public SQLXML						connectionCreateSQLXML				(String connectionId) throws SQLException;
	public boolean						connectionIsValid					(String connectionId, int timeout) throws SQLException;
//	-public void						connectionSetClientInfo				(String connectionId, String name, String value) throws SQLClientInfoException;
//	-public void						connectionSetClientInfo				(String connectionId, Properties properties) throws SQLClientInfoException;
//	-public String						connectionGetClientInfo				(String connectionId, String name) throws SQLException;
//	-public Properties					connectionGetClientInfo				(String connectionId) throws SQLException;
//	-public Array						connectionCreateArrayOf				(String connectionId, String typeName, Object[] elements) throws SQLException;
//	-public Struct						connectionCreateStruct				(String connectionId, String typeName, Object[] attributes) throws SQLException;
//	-public void						connectionGetSchema					(String connectionId, String schema) throws SQLException;
//	-public String						connectionGetSchema					(String connectionId) throws SQLException;
//	-public void						connectionAbort						(String connectionId, Executor executor) throws SQLException;
//	-public void						connectionSetNetworkTimeout			(String connectionId, Executor executor, int milliseconds) throws SQLException;
//	-public int							connectionGetNetworkTimeout			(String connectionId) throws SQLException;

//	+public <T> T						statementUnwrap						(String statementId, Class<T> iface) throws SQLException;
//	+public boolean						statementIsWrapperFor				(String statementId, Class<?> iface) throws SQLException;
	public String /*ResultSet*/			statementExecuteQuery				(String statementId, String sql) throws SQLException;
	public int							statementExecuteUpdate				(String statementId, String sql) throws SQLException;
	public void							statementClose						(String statementId) throws SQLException;
//	+public int							statementGetMaxFieldSize			(String statementId) throws SQLException;
//	+public void						statementSetMaxFieldSize			(String statementId, int max) throws SQLException;
	public int							statementGetMaxRows					(String statementId) throws SQLException;
	public void							statementSetMaxRows					(String statementId, int max) throws SQLException;
//	+public void						statementSetEscapeProcessing		(String statementId, boolean enable) throws SQLException;
	public int							statementGetQueryTimeout			(String statementId) throws SQLException;
	public void							statementSetQueryTimeout			(String statementId, int seconds) throws SQLException;
	public void							statementCancel						(String statementId) throws SQLException;
//	+public SQLWarning					statementGetWarnings				(String statementId) throws SQLException;
//	+public void						statementClearWarnings				(String statementId) throws SQLException;
//	+public void						statementSetCursorName				(String statementId, String name) throws SQLException;
	public boolean						statementExecute					(String statementId, String sql) throws SQLException;
	public String /*ResultSet*/			statementGetResultSet				(String statementId) throws SQLException;
	public int							statementGetUpdateCount				(String statementId) throws SQLException;
	public boolean						statementGetMoreResults				(String statementId) throws SQLException;
//	+public void						statementSetFetchDirection			(String statementId, int direction) throws SQLException;
//	+public int							statementGetFetchDirection			(String statementId) throws SQLException;
	public void							statementSetFetchSize				(String statementId, int rows) throws SQLException;
	public int							statementGetFetchSize				(String statementId) throws SQLException;
//	+public int							statementGetResultSetConcurrency	(String statementId) throws SQLException;
//	+public int							statementGetResultSetType			(String statementId) throws SQLException;
	public void							statementAddBatch					(String statementId, String sql) throws SQLException;
	public void							statementClearBatch					(String statementId) throws SQLException;
	public int[]						statementExecuteBatch				(String statementId) throws SQLException;
	public String /*Connection*/		statementGetConnection				(String statementId) throws SQLException;
	public boolean						statementGetMoreResults2			(String statementId, int current) throws SQLException;
	public String /*ResultSet*/			statementGetGeneratedKeys			(String statementId) throws SQLException;
	public int							statementExecuteUpdate2				(String statementId, String sql, int autoGeneratedKeys) throws SQLException;
	public int							statementExecuteUpdate3				(String statementId, String sql, int[] columnIndexes) throws SQLException;
	public int							statementExecuteUpdate4				(String statementId, String sql, String[] columnNames) throws SQLException;
	public boolean						statementExecute2					(String statementId, String sql, int autoGeneratedKeys) throws SQLException;
	public boolean						statementExecute3					(String statementId, String sql, int[] columnIndexes) throws SQLException;
	public boolean						statementExecute4					(String statementId, String sql, String[] columnNames) throws SQLException;
//	+public int							statementGetResultSetHoldability	(String statementId) throws SQLException;
	public boolean						statementIsClosed					(String statementId) throws SQLException;
//	+public void						statementSetPoolable				(String statementId, boolean poolable) throws SQLException;
//	+public boolean						statementIsPoolable					(String statementId) throws SQLException;
	public void							statementCloseOnCompletion			(String statementId) throws SQLException;
	public boolean						statementIsCloseOnCompletion		(String statementId) throws SQLException;

	public String						preparedStatementExecuteQuery			(String preparedStatementId) throws SQLException;
	public int							preparedStatementExecuteUpdate			(String preparedStatementId) throws SQLException;
	public void							preparedStatementSetNull				(String preparedStatementId, int parameterIndex, int sqlType) throws SQLException;
	public void							preparedStatementSetBoolean				(String preparedStatementId, int parameterIndex, boolean x) throws SQLException;
	public void							preparedStatementSetByte				(String preparedStatementId, int parameterIndex, byte x) throws SQLException;
	public void							preparedStatementSetShort				(String preparedStatementId, int parameterIndex, short x) throws SQLException;
	public void							preparedStatementSetInt					(String preparedStatementId, int parameterIndex, int x) throws SQLException;
	public void							preparedStatementSetLong				(String preparedStatementId, int parameterIndex, long x) throws SQLException;
	public void							preparedStatementSetFloat				(String preparedStatementId, int parameterIndex, float x) throws SQLException;
	public void							preparedStatementSetDouble				(String preparedStatementId, int parameterIndex, double x) throws SQLException;
	public void							preparedStatementSetBigDecimal			(String preparedStatementId, int parameterIndex, BigDecimal x) throws SQLException;
	public void							preparedStatementSetString				(String preparedStatementId, int parameterIndex, String x) throws SQLException;
	public void							preparedStatementSetBytes				(String preparedStatementId, int parameterIndex, byte[] x) throws SQLException;
	public void							preparedStatementSetDate				(String preparedStatementId, int parameterIndex, Date x) throws SQLException;
	public void							preparedStatementSetTime				(String preparedStatementId, int parameterIndex, Time x) throws SQLException;
	public void							preparedStatementSetTimestamp			(String preparedStatementId, int parameterIndex, Timestamp x) throws SQLException;
	public void							preparedStatementSetAsciiStream			(String preparedStatementId, int parameterIndex, InputStream x, int length) throws SQLException;
	public void							preparedStatementSetUnicodeStream		(String preparedStatementId, int parameterIndex, InputStream x, int length) throws SQLException;
	public void							preparedStatementSetBinaryStream		(String preparedStatementId, int parameterIndex, InputStream x, int length) throws SQLException;
	public void							preparedStatementClearParameters		(String preparedStatementId) throws SQLException;
	public void							preparedStatementSetObject				(String preparedStatementId, int parameterIndex, Object x, int targetSqlType) throws SQLException;
	public void							preparedStatementSetObject2				(String preparedStatementId, int parameterIndex, Object x) throws SQLException;
	public boolean						preparedStatementExecute				(String preparedStatementId) throws SQLException;
	public void							preparedStatementAddBatch				(String preparedStatementId) throws SQLException;
	public void							preparedStatementSetCharacterStream		(String preparedStatementId, int parameterIndex, Reader reader, int length) throws SQLException;
//	-public void						preparedStatementSetRef					(String preparedStatementId, int parameterIndex, Ref x) throws SQLException;
//	-public void						preparedStatementSetBlob				(String preparedStatementId, int parameterIndex, Blob x) throws SQLException;
//	-public void						preparedStatementSetClob				(String preparedStatementId, int parameterIndex, Clob x) throws SQLException;
//	-public void						preparedStatementSetArray				(String preparedStatementId, int parameterIndex, Array x) throws SQLException;
	public RowSetMetaDataImpl /*ResultSetMetaData*/
										preparedStatementGetMetaData			(String preparedStatementId) throws SQLException;
	public void							preparedStatementSetDate2				(String preparedStatementId, int parameterIndex, Date x, Calendar cal) throws SQLException;
	public void							preparedStatementSetTime2				(String preparedStatementId, int parameterIndex, Time x, Calendar cal) throws SQLException;
	public void							preparedStatementSetTimestamp2			(String preparedStatementId, int parameterIndex, Timestamp x, Calendar cal) throws SQLException;
	public void							preparedStatementSetNull2				(String preparedStatementId, int parameterIndex, int sqlType, String typeName) throws SQLException;
//	-public void						preparedStatementSetURL					(String preparedStatementId, int parameterIndex, URL x) throws SQLException;
	public String /*ParameterMetaData*/	preparedStatementGetParameterMetaData	(String preparedStatementId) throws SQLException;
	public void							preparedStatementSetRowId				(String preparedStatementId, int parameterIndex, RowId x) throws SQLException;
	public void							preparedStatementSetNString				(String preparedStatementId, int parameterIndex, String value) throws SQLException;
	public void							preparedStatementSetNCharacterStream	(String preparedStatementId, int parameterIndex, Reader value, long length) throws SQLException;
	public void							preparedStatementSetNClob				(String preparedStatementId, int parameterIndex, NClob value) throws SQLException;
	public void							preparedStatementSetClob				(String preparedStatementId, int parameterIndex, Reader reader, long length) throws SQLException;
	public void							preparedStatementSetBlob				(String preparedStatementId, int parameterIndex, InputStream inputStream, long length) throws SQLException;
	public void							preparedStatementSetNClob2				(String preparedStatementId, int parameterIndex, Reader reader, long length) throws SQLException;
	public void							preparedStatementSetSQLXML				(String preparedStatementId, int parameterIndex, SQLXML xmlObject) throws SQLException;
	public void							preparedStatementSetObject3				(String preparedStatementId, int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException;
	public void							preparedStatementSetAsciiStream2		(String preparedStatementId, int parameterIndex, InputStream x, long length) throws SQLException;
	public void							preparedStatementSetBinaryStream2		(String preparedStatementId, int parameterIndex, InputStream x, long length) throws SQLException;
	public void							preparedStatementSetCharacterStream2	(String preparedStatementId, int parameterIndex, Reader reader, long length) throws SQLException;
	public void							preparedStatementSetAsciiStream3		(String preparedStatementId, int parameterIndex, InputStream x) throws SQLException;
	public void							preparedStatementSetBinaryStream3		(String preparedStatementId, int parameterIndex, InputStream x) throws SQLException;
	public void							preparedStatementSetCharacterStream3	(String preparedStatementId, int parameterIndex, Reader reader) throws SQLException;
	public void							preparedStatementSetNCharacterStream2	(String preparedStatementId, int parameterIndex, Reader value) throws SQLException;
	public void							preparedStatementSetClob2				(String preparedStatementId, int parameterIndex, Reader reader) throws SQLException;
	public void							preparedStatementSetBlob2				(String preparedStatementId, int parameterIndex, InputStream inputStream) throws SQLException;
	public void							preparedStatementSetNClob3				(String preparedStatementId, int parameterIndex, Reader reader) throws SQLException;
	
//	+public <T> T						databaseMetaDataUnwrap													(String databaseMetaDataId, Class<T> iface) throws SQLException;
//	+public boolean 					databaseMetaDataIsWrapperFor											(String databaseMetaDataId, Class<?> iface) throws SQLException;
//	+public boolean						databaseMetaDataAllProceduresAreCallable								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataAllTablesAreSelectable									(String databaseMetaDataId) throws SQLException;
	public String 						databaseMetaDataGetURL													(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetUserName												(String databaseMetaDataId) throws SQLException;
	public boolean 						databaseMetaDataIsReadOnly												(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataNullsAreSortedHigh										(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataNullsAreSortedLow										(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataNullsAreSortedAtStart									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataNullsAreSortedAtEnd										(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetDatabaseProductName									(String databaseMetaDataId) throws SQLException;
	public String 						databaseMetaDataGetDatabaseProductVersion								(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetDriverName											(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetDriverVersion										(String databaseMetaDataId) throws SQLException;
//	+public int							databaseMetaDataGetDriverMajorVersion									(String databaseMetaDataId);
//	+public int							databaseMetaDataGetDriverMinorVersion									(String databaseMetaDataId);
//	+public boolean						databaseMetaDataUsesLocalFiles											(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataUsesLocalFilePerTable									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsMixedCaseIdentifiers							(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataStoresUpperCaseIdentifiers								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataStoresLowerCaseIdentifiers								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataStoresMixedCaseIdentifiers								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsMixedCaseQuotedIdentifiers						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataStoresUpperCaseQuotedIdentifiers						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataStoresLowerCaseQuotedIdentifiers						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataStoresMixedCaseQuotedIdentifiers						(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetIdentifierQuoteString								(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetSQLKeywords											(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetNumericFunctions										(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetStringFunctions										(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetSystemFunctions										(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetTimeDateFunctions									(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetSearchStringEscape									(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetExtraNameCharacters									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsAlterTableWithAddColumn							(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsAlterTableWithDropColumn						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsColumnAliasing									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataNullPlusNonNullIsNull									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsConvert											(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsConvert											(String databaseMetaDataId, int fromType, int toType) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsTableCorrelationNames							(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsDifferentTableCorrelationNames					(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsExpressionsInOrderBy							(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsOrderByUnrelated								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsGroupBy											(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsGroupByUnrelated								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsGroupByBeyondSelect								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsLikeEscapeClause								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsMultipleResultSets								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsMultipleTransactions							(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsNonNullableColumns								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsMinimumSQLGrammar								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsCoreSQLGrammar									(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsExtendedSQLGrammar								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsANSI92EntryLevelSQL								(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsANSI92IntermediateSQL							(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsANSI92FullSQL									(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsIntegrityEnhancementFacility					(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsOuterJoins										(String databaseMetaDataId) throws SQLException;
	public boolean 						databaseMetaDataSupportsFullOuterJoins									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsLimitedOuterJoins								(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetSchemaTerm											(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetProcedureTerm										(String databaseMetaDataId) throws SQLException;
//	+public String 						databaseMetaDataGetCatalogTerm											(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataIsCatalogAtStart										(String databaseMetaDataId) throws SQLException;
//	+public String	 					databaseMetaDataGetCatalogSeparator										(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSchemasInDataManipulation						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSchemasInProcedureCalls							(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSchemasInTableDefinitions						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSchemasInIndexDefinitions						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSchemasInPrivilegeDefinitions					(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsCatalogsInDataManipulation						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsCatalogsInProcedureCalls						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsCatalogsInTableDefinitions						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsCatalogsInIndexDefinitions						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsCatalogsInPrivilegeDefinitions					(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsPositionedDelete								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsPositionedUpdate								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSelectForUpdate									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsStoredProcedures								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSubqueriesInComparisons							(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSubqueriesInExists								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSubqueriesInIns									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSubqueriesInQuantifieds							(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsCorrelatedSubqueries							(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsUnion											(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsUnionAll										(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsOpenCursorsAcrossCommit							(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsOpenCursorsAcrossRollback						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsOpenStatementsAcrossCommit						(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsOpenStatementsAcrossRollback					(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxBinaryLiteralLength								(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxCharLiteralLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxColumnNameLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxColumnsInGroupBy									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxColumnsInIndex									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxColumnsInOrderBy									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxColumnsInSelect									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxColumnsInTable									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxConnections										(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxCursorNameLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxIndexLength										(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxSchemaNameLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxProcedureNameLength								(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxCatalogNameLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxRowSize											(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataDoesMaxRowSizeIncludeBlobs								(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxStatementLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxStatements										(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxTableNameLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxTablesInSelect									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetMaxUserNameLength									(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetDefaultTransactionIsolation							(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsTransactions									(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsTransactionIsolationLevel						(String databaseMetaDataId, int level) throws SQLException;
//	+public boolean						databaseMetaDataSupportsDataDefinitionAndDataManipulationTransactions	(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataSupportsDataManipulationTransactionsOnly				(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataDataDefinitionCausesTransactionCommit					(String databaseMetaDataId) throws SQLException;
//	+public boolean						databaseMetaDataDataDefinitionIgnoredInTransactions						(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetProcedures											(String databaseMetaDataId, String catalog, String schemaPattern, String procedureNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetProcedureColumns										(String databaseMetaDataId, String catalog, String schemaPattern, String procedureNamePattern, String columnNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetTables												(String databaseMetaDataId, String catalog, String schemaPattern, String tableNamePattern, String[] types) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetSchemas												(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetCatalogs												(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetTableTypes											(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetColumns												(String databaseMetaDataId, String catalog, String schemaPattern, String tableNamePattern, String columnNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetColumnPrivileges										(String databaseMetaDataId, String catalog, String schema, String table, String columnNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetTablePrivileges										(String databaseMetaDataId, String catalog, String schemaPattern, String tableNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetBestRowIdentifier									(String databaseMetaDataId, String catalog, String schema, String table, int scope, boolean nullable) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetVersionColumns										(String databaseMetaDataId, String catalog, String schema, String table) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetPrimaryKeys											(String databaseMetaDataId, String catalog, String schema, String table) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetImportedKeys											(String databaseMetaDataId, String catalog, String schema, String table) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetExportedKeys											(String databaseMetaDataId, String catalog, String schema, String table) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetCrossReference										(String databaseMetaDataId, String parentCatalog, String parentSchema, String parentTable, String foreignCatalog, String foreignSchema, String foreignTable) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetTypeInfo												(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetIndexInfo											(String databaseMetaDataId, String catalog, String schema, String table, boolean unique, boolean approximate) throws SQLException;
//	+public boolean						databaseMetaDataSupportsResultSetType									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataSupportsResultSetConcurrency							(String databaseMetaDataId, int type, int concurrency) throws SQLException;
//	+public boolean						databaseMetaDataOwnUpdatesAreVisible									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataOwnDeletesAreVisible									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataOwnInsertsAreVisible									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataOthersUpdatesAreVisible									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataOthersDeletesAreVisible									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataOthersInsertsAreVisible									(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataUpdatesAreDetected										(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataDeletesAreDetected										(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataInsertsAreDetected										(String databaseMetaDataId, int type) throws SQLException;
//	+public boolean						databaseMetaDataSupportsBatchUpdates									(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetUDTs													(String databaseMetaDataId, String catalog, String schemaPattern, String typeNamePattern, int[] types) throws SQLException;
	public String /*Connection*/		databaseMetaDataGetConnection											(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsSavepoints										(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsNamedParameters									(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsMultipleOpenResults								(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsGetGeneratedKeys								(String databaseMetaDataId) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetSuperTypes											(String databaseMetaDataId, String catalog, String schemaPattern, String typeNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetSuperTables											(String databaseMetaDataId, String catalog, String schemaPattern, String tableNamePattern) throws SQLException;
	public String /*ResultSet*/			databaseMetaDataGetAttributes											(String databaseMetaDataId, String catalog, String schemaPattern, String typeNamePattern, String attributeNamePattern) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsResultSetHoldability							(String databaseMetaDataId, int holdability) throws SQLException;
//	+public int 						databaseMetaDataGetResultSetHoldability									(String databaseMetaDataId) throws SQLException;
	public int 							databaseMetaDataGetDatabaseMajorVersion									(String databaseMetaDataId) throws SQLException;
	public int 							databaseMetaDataGetDatabaseMinorVersion									(String databaseMetaDataId) throws SQLException;
//	+public int							databaseMetaDataGetJDBCMajorVersion										(String databaseMetaDataId) throws SQLException;
//	+public int							databaseMetaDataGetJDBCMinorVersion										(String databaseMetaDataId) throws SQLException;
//	+public int 						databaseMetaDataGetSQLStateType											(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataLocatorsUpdateCopy										(String databaseMetaDataId) throws SQLException;
//	+public boolean 					databaseMetaDataSupportsStatementPooling								(String databaseMetaDataId) throws SQLException;
//	-public RowIdLifetime				databaseMetaDataGetRowIdLifetime										(String databaseMetaDataId) throws SQLException;
//	-public ResultSet					databaseMetaDataGetSchemas												(String databaseMetaDataId, String catalog, String schemaPattern) throws SQLException;
//	-public boolean 					databaseMetaDataSupportsStoredFunctionsUsingCallSyntax					(String databaseMetaDataId) throws SQLException;
//	-public boolean 					databaseMetaDataAutoCommitFailureClosesAllResultSets					(String databaseMetaDataId) throws SQLException;
//	-public ResultSet					databaseMetaDataGetClientInfoProperties									(String databaseMetaDataId) throws SQLException;
//	-public ResultSet					databaseMetaDataGetFunctions											(String databaseMetaDataId, String catalog, String schemaPattern, String functionNamePattern) throws SQLException;
//	-public ResultSet					databaseMetaDataGetFunctionColumns										(String databaseMetaDataId, String catalog, String schemaPattern, String functionNamePattern, String columnNamePattern) throws SQLException;
//	-public ResultSet					databaseMetaDataGetPseudoColumns										(String databaseMetaDataId, String catalog, String schemaPattern, String tableNamePattern, String columnNamePattern) throws SQLException;
//	-public boolean 					databaseMetaDataGeneratedKeyAlwaysReturned								(String databaseMetaDataId) throws SQLException;
	
	public int							savepointGetSavepointId					(String savepointId) throws SQLException;
	public String						savepointGetSavepointName				(String savepointId) throws SQLException;

//	+public int							resultSetMetaDataGetColumnCount			(String resultSetMetaDataId) throws SQLException;
//	+public boolean						resultSetMetaDataIsAutoIncrement		(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean 					resultSetMetaDataIsCaseSensitive		(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean 					resultSetMetaDataIsSearchable			(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean 					resultSetMetaDataIsCurrency				(String resultSetMetaDataId, int column) throws SQLException;
//	+public int 						resultSetMetaDataIsNullable				(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean						resultSetMetaDataIsSigned				(String resultSetMetaDataId, int column) throws SQLException;
//	+public int							resultSetMetaDataGetColumnDisplaySize	(String resultSetMetaDataId, int column) throws SQLException;
//	+public String 						resultSetMetaDataGetColumnLabel			(String resultSetMetaDataId, int column) throws SQLException;
//	+public String						resultSetMetaDataGetColumnName			(String resultSetMetaDataId, int column) throws SQLException;
//	+public String						resultSetMetaDataGetSchemaName			(String resultSetMetaDataId, int column) throws SQLException;
//	+public int							resultSetMetaDataGetPrecision			(String resultSetMetaDataId, int column) throws SQLException;
//	+public int							resultSetMetaDataGetScale				(String resultSetMetaDataId, int column) throws SQLException;
//	+public String						resultSetMetaDataGetTableName			(String resultSetMetaDataId, int column) throws SQLException;
//	+public String						resultSetMetaDataGetCatalogName			(String resultSetMetaDataId, int column) throws SQLException;
//	+public int							resultSetMetaDataGetColumnType			(String resultSetMetaDataId, int column) throws SQLException;
//	+public String						resultSetMetaDataGetColumnTypeName		(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean						resultSetMetaDataIsReadOnly				(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean						resultSetMetaDataIsWritable				(String resultSetMetaDataId, int column) throws SQLException;
//	+public boolean						resultSetMetaDataIsDefinitelyWritable	(String resultSetMetaDataId, int column) throws SQLException;
//	+public String						resultSetMetaDataGetColumnClassName		(String resultSetMetaDataId, int column) throws SQLException;

	public int							parameterMetaDataGetParameterCount		(String parameterMetaDataId) throws SQLException;
//	+public int							parameterMetaDataIsNullable				(String parameterMetaDataId, int param) throws SQLException;
//	+public boolean						parameterMetaDataIsSigned				(String parameterMetaDataId, int param) throws SQLException;
//	+public int							parameterMetaDataGetPrecision			(String parameterMetaDataId, int param) throws SQLException;
//	+public int							parameterMetaDataGetScale				(String parameterMetaDataId, int param) throws SQLException;
	public int							parameterMetaDataGetParameterType		(String parameterMetaDataId, int param) throws SQLException;
	public String						parameterMetaDataGetParameterTypeName	(String parameterMetaDataId, int param) throws SQLException;
	public String						parameterMetaDataGetParameterClassName	(String parameterMetaDataId, int param) throws SQLException;
//	+public int							parameterMetaDataGetParameterMode		(String parameterMetaDataId, int param) throws SQLException;
	
//	+public <T> T						resultSetUnwrap						(String resultSetId, Class<T> iface) throws SQLException;
//	+public boolean						resultSetIsWrapperFor				(String resultSetId, Class<?> iface) throws SQLException;
//	+public boolean						resultSetNext						(String resultSetId) throws SQLException;
	public void							resultSetClose						(String resultSetId) throws SQLException;
//	+public boolean						resultSetWasNull					(String resultSetId) throws SQLException;
//	+public String						resultSetGetString					(String resultSetId, int columnIndex) throws SQLException;
//	+public boolean						resultSetGetBoolean					(String resultSetId, int columnIndex) throws SQLException;
//	+public byte						resultSetGetByte					(String resultSetId, int columnIndex) throws SQLException;
//	+public short						resultSetGetShort					(String resultSetId, int columnIndex) throws SQLException;
//	+public int							resultSetGetInt						(String resultSetId, int columnIndex) throws SQLException;
//	+public long						resultSetGetLong					(String resultSetId, int columnIndex) throws SQLException;
//	+public float						resultSetGetFloat					(String resultSetId, int columnIndex) throws SQLException;
//	+public double						resultSetGetDouble					(String resultSetId, int columnIndex) throws SQLException;
//	+public BigDecimal					resultSetGetBigDecimal				(String resultSetId, int columnIndex, int scale) throws SQLException;
//	+public byte[]						resultSetGetBytes					(String resultSetId, int columnIndex) throws SQLException;
//	+public Date						resultSetGetDate					(String resultSetId, int columnIndex) throws SQLException;
//	+public Time						resultSetGetTime					(String resultSetId, int columnIndex) throws SQLException;
//	+public Timestamp					resultSetGetTimestamp				(String resultSetId, int columnIndex) throws SQLException;
//	+public InputStream					resultSetGetAsciiStream				(String resultSetId, int columnIndex) throws SQLException;
//	+public InputStream					resultSetGetUnicodeStream			(String resultSetId, int columnIndex) throws SQLException;
//	+public InputStream					resultSetGetBinaryStream			(String resultSetId, int columnIndex) throws SQLException;
//	+public String						resultSetGetString2					(String resultSetId, String columnLabel) throws SQLException;
//	+public boolean						resultSetGetBoolean2				(String resultSetId, String columnLabel) throws SQLException;
//	+public byte						resultSetGetByte2					(String resultSetId, String columnLabel) throws SQLException;
//	+public short						resultSetGetShort2					(String resultSetId, String columnLabel) throws SQLException;
//	+public int							resultSetGetInt2					(String resultSetId, String columnLabel) throws SQLException;
//	+public long						resultSetGetLong2					(String resultSetId, String columnLabel) throws SQLException;
//	+public float						resultSetGetFloat2					(String resultSetId, String columnLabel) throws SQLException;
//	+public double						resultSetGetDouble2					(String resultSetId, String columnLabel) throws SQLException;
//	+public BigDecimal					resultSetGetBigDecimal2				(String resultSetId, String columnLabel, int scale) throws SQLException;
//	+public byte[]						resultSetGetBytes2					(String resultSetId, String columnLabel) throws SQLException;
//	+public Date						resultSetGetDate2					(String resultSetId, String columnLabel) throws SQLException;
//	+public Time						resultSetGetTime2					(String resultSetId, String columnLabel) throws SQLException;
//	+public Timestamp					resultSetGetTimestamp2				(String resultSetId, String columnLabel) throws SQLException;
//	+public InputStream					resultSetGetAsciiStream2			(String resultSetId, String columnLabel) throws SQLException;
//	+public InputStream					resultSetGetUnicodeStream2			(String resultSetId, String columnLabel) throws SQLException;
//	+public InputStream					resultSetGetBinaryStream2			(String resultSetId, String columnLabel) throws SQLException;
//	+public SQLWarning					resultSetGetWarnings				(String resultSetId) throws SQLException;
//	+public void						resultSetClearWarnings				(String resultSetId) throws SQLException;
//	+public String						resultSetGetCursorName				(String resultSetId) throws SQLException;
//	+public ResultSetMetaData			resultSetGetMetaData				(String resultSetId) throws SQLException;
//	+public Object						resultSetGetObject					(String resultSetId, int columnIndex) throws SQLException;
//	+public Object						resultSetGetObject2					(String resultSetId, String columnLabel) throws SQLException;
//	+public int							resultSetFindColumn					(String resultSetId, String columnLabel) throws SQLException;
//	+public Reader						resultSetGetCharacterStream			(String resultSetId, int columnIndex) throws SQLException;
//	+public Reader						resultSetGetCharacterStream2		(String resultSetId, String columnLabel) throws SQLException;
//	+public BigDecimal					resultSetGetBigDecimal3				(String resultSetId, int columnIndex) throws SQLException;
//	+public BigDecimal					resultSetGetBigDecimal4				(String resultSetId, String columnLabel) throws SQLException;
//	+public boolean						resultSetIsBeforeFirst				(String resultSetId) throws SQLException;
//	+public boolean						resultSetIsAfterLast				(String resultSetId) throws SQLException;
//	+public boolean						resultSetIsFirst					(String resultSetId) throws SQLException;
//	-public boolean						resultSetIsLast						(String resultSetId) throws SQLException;
//	-public void						resultSetBeforeFirst				(String resultSetId) throws SQLException;
//	-public void						resultSetAfterLast					(String resultSetId) throws SQLException;
//	-public boolean						resultSetFirst						(String resultSetId) throws SQLException;
//	-public boolean						resultSetLast						(String resultSetId) throws SQLException;
//	+public int							resultSetGetRow						(String resultSetId) throws SQLException;
//	-public boolean						resultSetAbsolute					(String resultSetId, int row) throws SQLException;
//	-public boolean						resultSetRelative					(String resultSetId, int rows) throws SQLException;
//	-public boolean						resultSetPrevious					(String resultSetId) throws SQLException;
//	+public void						resultSetSetFetchDirection			(String resultSetId, int direction) throws SQLException;
//	+public int							resultSetGetFetchDirection			(String resultSetId) throws SQLException;
	public void							resultSetSetFetchSize				(String resultSetId, int rows) throws SQLException;
	public int							resultSetGetFetchSize				(String resultSetId) throws SQLException;
//	+public int							resultSetGetType					(String resultSetId) throws SQLException;
//	+public int							resultSetGetConcurrency				(String resultSetId) throws SQLException;
//	+public boolean						resultSetRowUpdated					(String resultSetId) throws SQLException;
//	+public boolean						resultSetRowInserted				(String resultSetId) throws SQLException;
//	+public boolean						resultSetRowDeleted					(String resultSetId) throws SQLException;
//	-public void						resultSetUpdateNull					(String resultSetId, int columnIndex) throws SQLException;
//	-public void						resultSetUpdateBoolean				(String resultSetId, int columnIndex, boolean x) throws SQLException;
//	-public void						resultSetUpdateByte					(String resultSetId, int columnIndex, byte x) throws SQLException;
//	-public void						resultSetUpdateShort				(String resultSetId, int columnIndex, short x) throws SQLException;
//	-public void						resultSetUpdateInt					(String resultSetId, int columnIndex, int x) throws SQLException;
//	-public void						resultSetUpdateLong					(String resultSetId, int columnIndex, long x) throws SQLException;
//	-public void						resultSetUpdateFloat				(String resultSetId, int columnIndex, float x) throws SQLException;
//	-public void						resultSetUpdateDouble				(String resultSetId, int columnIndex, double x) throws SQLException;
//	-public void						resultSetUpdateBigDecimal			(String resultSetId, int columnIndex, BigDecimal x) throws SQLException;
//	-public void						resultSetUpdateString				(String resultSetId, int columnIndex, String x) throws SQLException;
//	-public void						resultSetUpdateBytes				(String resultSetId, int columnIndex, byte[] x) throws SQLException;
//	-public void						resultSetUpdateDate					(String resultSetId, int columnIndex, Date x) throws SQLException;
//	-public void						resultSetUpdateTime					(String resultSetId, int columnIndex, Time x) throws SQLException;
//	-public void						resultSetUpdateTimestamp			(String resultSetId, int columnIndex, Timestamp x) throws SQLException;
//	-public void						resultSetUpdateAsciiStream			(String resultSetId, int columnIndex, InputStream x, int length) throws SQLException;
//	-public void						resultSetUpdateBinaryStream			(String resultSetId, int columnIndex, InputStream x, int length) throws SQLException;
//	-public void						resultSetUpdateCharacterStream		(String resultSetId, int columnIndex, Reader x, int length) throws SQLException;
//	-public void						resultSetUpdateObject				(String resultSetId, int columnIndex, Object x, int scaleOrLength) throws SQLException;
//	-public void						resultSetUpdateObject				(String resultSetId, int columnIndex, Object x) throws SQLException;
//	-public void						resultSetUpdateNull					(String resultSetId, String columnLabel) throws SQLException;
//	-public void						resultSetUpdateBoolean				(String resultSetId, String columnLabel, boolean x) throws SQLException;
//	-public void						resultSetUpdateByte					(String resultSetId, String columnLabel, byte x) throws SQLException;
//	-public void						resultSetUpdateShort				(String resultSetId, String columnLabel, short x) throws SQLException;
//	-public void						resultSetUpdateInt					(String resultSetId, String columnLabel, int x) throws SQLException;
//	-public void						resultSetUpdateLong					(String resultSetId, String columnLabel, long x) throws SQLException;
//	-public void						resultSetUpdateFloat				(String resultSetId, String columnLabel, float x) throws SQLException;
//	-public void						resultSetUpdateDouble				(String resultSetId, String columnLabel, double x) throws SQLException;
//	-public void						resultSetUpdateBigDecimal			(String resultSetId, String columnLabel, BigDecimal x) throws SQLException;
//	-public void						resultSetUpdateString				(String resultSetId, String columnLabel, String x) throws SQLException;
//	-public void						resultSetUpdateBytes				(String resultSetId, String columnLabel, byte[] x) throws SQLException;
//	-public void						resultSetUpdateDate					(String resultSetId, String columnLabel, Date x) throws SQLException;
//	-public void						resultSetUpdateTime					(String resultSetId, String columnLabel, Time x) throws SQLException;
//	-public void						resultSetUpdateTimestamp			(String resultSetId, String columnLabel, Timestamp x) throws SQLException;
//	-public void						resultSetUpdateAsciiStream			(String resultSetId, String columnLabel, InputStream x, int length) throws SQLException;
//	-public void						resultSetUpdateBinaryStream			(String resultSetId, String columnLabel, InputStream x, int length) throws SQLException;
//	-public void						resultSetUpdateCharacterStream		(String resultSetId, String columnLabel, Reader reader, int length) throws SQLException;
//	-public void						resultSetUpdateObject				(String resultSetId, String columnLabel, Object x, int scaleOrLength) throws SQLException;
//	-public void						resultSetUpdateObject				(String resultSetId, String columnLabel, Object x) throws SQLException;
//	-public void						resultSetInsertRow					(String resultSetId) throws SQLException;
//	-public void						resultSetUpdateRow					(String resultSetId) throws SQLException;
//	-public void						resultSetDeleteRow					(String resultSetId) throws SQLException;
//	-public void						resultSetRefreshRow					(String resultSetId) throws SQLException;
//	-public void						resultSetCancelRowUpdates			(String resultSetId) throws SQLException;
//	-public void						resultSetMoveToInsertRow			(String resultSetId) throws SQLException;
//	-public void						resultSetMoveToCurrentRow			(String resultSetId) throws SQLException;
	public String /*Statement*/			resultSetGetStatement				(String resultSetId) throws SQLException;
//	-public Object						resultSetGetObject					(String resultSetId, int columnIndex, Map<String, Class<?>> map) throws SQLException;
//	-public Ref							resultSetGetRef						(String resultSetId, int columnIndex) throws SQLException;
//	-public Blob						resultSetGetBlob					(String resultSetId, int columnIndex) throws SQLException;
//	public Clob							resultSetGetClob					(String resultSetId, int columnIndex) throws SQLException;
//	-public Array						resultSetGetArray					(String resultSetId, int columnIndex) throws SQLException;
//	-public Object						resultSetGetObject					(String resultSetId, String columnLabel, Map<String, Class<?>> map) throws SQLException;
//	-public Ref							resultSetGetRef						(String resultSetId, String columnLabel) throws SQLException;
//	-public Blob						resultSetGetBlob					(String resultSetId, String columnLabel) throws SQLException;
//	public Clob							resultSetGetClob					(String resultSetId, String columnLabel) throws SQLException;
//	-public Array						resultSetGetArray					(String resultSetId, String columnLabel) throws SQLException;
//	+public Date						resultSetGetDate					(String resultSetId, int columnIndex, Calendar cal) throws SQLException;
//	+public Date						resultSetGetDate					(String resultSetId, String columnLabel, Calendar cal) throws SQLException;
//	+public Time						resultSetGetTime					(String resultSetId, int columnIndex, Calendar cal) throws SQLException;
//	+public Time						resultSetGetTime					(String resultSetId, String columnLabel, Calendar cal) throws SQLException;
//	+public Timestamp					resultSetGetTimestamp				(String resultSetId, int columnIndex, Calendar cal) throws SQLException;
//	+public Timestamp					resultSetGetTimestamp				(String resultSetId, String columnLabel, Calendar cal) throws SQLException;
//	-public URL							resultSetGetURL						(String resultSetId, int columnIndex) throws SQLException;
//	-public URL							resultSetGetURL						(String resultSetId, String columnLabel) throws SQLException;
//	-public void						resultSetUpdateRef					(String resultSetId, int columnIndex, Ref x) throws SQLException;
//	-public void						resultSetUpdateRef					(String resultSetId, String columnLabel, Ref x) throws SQLException;
//	-public void						resultSetUpdateBlob					(String resultSetId, int columnIndex, Blob x) throws SQLException;
//	-public void						resultSetUpdateBlob					(String resultSetId, String columnLabel, Blob x) throws SQLException;
//	-public void						resultSetUpdateClob					(String resultSetId, int columnIndex, Clob x) throws SQLException;
//	-public void						resultSetUpdateClob					(String resultSetId, String columnLabel, Clob x) throws SQLException;
//	-public void						resultSetUpdateArray				(String resultSetId, int columnIndex, Array x) throws SQLException;
//	-public void						resultSetUpdateArray				(String resultSetId, String columnLabel, Array x) throws SQLException;
//	-public RowId						resultSetGetRowId					(String resultSetId, int columnIndex) throws SQLException;
//	-public RowId						resultSetGetRowId					(String resultSetId, String columnLabel) throws SQLException;
//	-public void						resultSetUpdateRowId				(String resultSetId, int columnIndex, RowId x) throws SQLException;
//	-public void						resultSetUpdateRowId				(String resultSetId, String columnLabel, RowId x) throws SQLException;
//	+public int							resultSetGetHoldability				(String resultSetId) throws SQLException;
//	+public boolean						resultSetIsClosed					(String resultSetId) throws SQLException;
//	-public void						resultSetUpdateNString				(String resultSetId, int columnIndex, String nString) throws SQLException;
//	-public void						resultSetUpdateNString				(String resultSetId, String columnLabel, String nString) throws SQLException;
//	-public void						resultSetUpdateNClob				(String resultSetId, int columnIndex, NClob nClob) throws SQLException;
//	-public void						resultSetUpdateNClob				(String resultSetId, String columnLabel, NClob nClob) throws SQLException;
//	-public NClob						resultSetGetNClob					(String resultSetId, int columnIndex) throws SQLException;
//	-public NClob						resultSetGetNClob					(String resultSetId, String columnLabel) throws SQLException;
//	-public SQLXML						resultSetGetSQLXML					(String resultSetId, int columnIndex) throws SQLException;
//	-public SQLXML						resultSetGetSQLXML					(String resultSetId, String columnLabel) throws SQLException;
//	-public void						resultSetUpdateSQLXML				(String resultSetId, int columnIndex, SQLXML xmlObject) throws SQLException;
//	-public void						resultSetUpdateSQLXML				(String resultSetId, String columnLabel, SQLXML xmlObject) throws SQLException;
//	-public String						resultSetGetNString					(String resultSetId, int columnIndex) throws SQLException;
//	-public String						resultSetGetNString					(String resultSetId, String columnLabel) throws SQLException;
//	-public Reader						resultSetGetNCharacterStream		(String resultSetId, int columnIndex) throws SQLException;
//	-public Reader						resultSetGetNCharacterStream		(String resultSetId, String columnLabel) throws SQLException;
//	-public void						resultSetUpdateNCharacterStream		(String resultSetId, int columnIndex, Reader x, long length) throws SQLException;
//	-public void						resultSetUpdateNCharacterStream		(String resultSetId, String columnLabel, Reader reader, long length) throws SQLException;
//	-public void						resultSetUpdateAsciiStream			(String resultSetId, int columnIndex, InputStream x, long length) throws SQLException;
//	-public void						resultSetUpdateBinaryStream			(String resultSetId, int columnIndex, InputStream x, long length) throws SQLException;
//	-public void						resultSetUpdateCharacterStream		(String resultSetId, int columnIndex, Reader x, long length) throws SQLException;
//	-public void						resultSetUpdateAsciiStream			(String resultSetId, String columnLabel, InputStream x, long length) throws SQLException;
//	-public void						resultSetUpdateBinaryStream			(String resultSetId, String columnLabel, InputStream x, long length) throws SQLException;
//	-public void						resultSetUpdateCharacterStream		(String resultSetId, String columnLabel, Reader reader, long length) throws SQLException;
//	-public void						resultSetUpdateBlob					(String resultSetId, int columnIndex, InputStream inputStream, long length) throws SQLException;
//	-public void						resultSetUpdateBlob					(String resultSetId, String columnLabel, InputStream inputStream, long length) throws SQLException;
//	-public void						resultSetUpdateClob					(String resultSetId, int columnIndex, Reader reader, long length) throws SQLException;
//	-public void						resultSetUpdateClob					(String resultSetId, String columnLabel, Reader reader, long length) throws SQLException;
//	-public void						resultSetUpdateNClob				(String resultSetId, int columnIndex, Reader reader, long length) throws SQLException;
//	-public void						resultSetUpdateNClob				(String resultSetId, String columnLabel, Reader reader, long length) throws SQLException;
//	-public void						resultSetUpdateNCharacterStream		(String resultSetId, int columnIndex, Reader x) throws SQLException;
//	-public void						resultSetUpdateNCharacterStream		(String resultSetId, String columnLabel, Reader reader) throws SQLException;
//	-public void						resultSetUpdateAsciiStream			(String resultSetId, int columnIndex, InputStream x) throws SQLException;
//	-public void						resultSetUpdateBinaryStream			(String resultSetId, int columnIndex, InputStream x) throws SQLException;
//	-public void						resultSetUpdateCharacterStream		(String resultSetId, int columnIndex, Reader x) throws SQLException;
//	-public void						resultSetUpdateAsciiStream			(String resultSetId, String columnLabel, InputStream x) throws SQLException;
//	-public void						resultSetUpdateBinaryStream			(String resultSetId, String columnLabel, InputStream x) throws SQLException;
//	-public void						resultSetUpdateCharacterStream		(String resultSetId, String columnLabel, Reader reader) throws SQLException;
//	-public void						resultSetUpdateBlob					(String resultSetId, int columnIndex, InputStream inputStream) throws SQLException;
//	-public void						resultSetUpdateBlob					(String resultSetId, String columnLabel, InputStream inputStream) throws SQLException;
//	-public void						resultSetUpdateClob					(String resultSetId, int columnIndex, Reader reader) throws SQLException;
//	-public void						resultSetUpdateClob					(String resultSetId, String columnLabel, Reader reader) throws SQLException;
//	-public void						resultSetUpdateNClob				(String resultSetId, int columnIndex, Reader reader) throws SQLException;
//	-public void						resultSetUpdateNClob				(String resultSetId, String columnLabel, Reader reader) throws SQLException;
//	-public <T> T						resultSetGetObject					(String resultSetId, int columnIndex, Class<T> type) throws SQLException;
//	-public <T> T						resultSetGetObject					(String resultSetIdString columnLabel, Class<T> type) throws SQLException;

}
